config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "manuals#index"
  resources :manuals, except: :index do
    resources :procedures, except: [:index, :show] do
      resources :comments, only: [:create, :destroy]
    end
    resources :releases, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resources :likes, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '料理レシピ' },
    { id: 2, name: '作業手順' },
    { id: 3, name: '操作方法' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :manuals
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :manual
  belongs_to :procedure

  validates :content, presence: true, length: { maximum: 200 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :manual
end

app/models/manual.rb
class Manual < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :release, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :reviews, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :title, length: { maximum: 20 }
    validates :category_id, numericality: { other_than: 0, message: 'を選択してください' }
  end
  validates :description, length: { maximum: 160 }

  def image_attach(converted_url)
    decoded_url = Base64.decode64(converted_url)
    filename = Time.zone.now.to_s + '.png'

    if Rails.env == 'development'
      # Local environment
      file_path = "#{Rails.root}/tmp/images/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    elsif Rails.env == 'production'
      # Production environment
      file_path = "/tmp/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    end
  end

  def image_attach_process(decoded_url, filename, file_path)
    File.open(file_path, 'wb') do |f|
      f.write(decoded_url)
    end
    image.attach(io: File.open(file_path), filename: filename)
    FileUtils.rm(file_path)
  end
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :manual
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 400 }

  def image_attach(converted_url)
    decoded_url = Base64.decode64(converted_url)
    filename = Time.zone.now.to_s + '.png'

    if Rails.env == 'development'
      # Local environment
      file_path = "#{Rails.root}/tmp/images/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    elsif Rails.env == 'production'
      # Production environment
      file_path = "/tmp/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    end
  end

  def image_attach_process(decoded_url, filename, file_path)
    File.open(file_path, 'wb') do |f|
      f.write(decoded_url)
    end
    image.attach(io: File.open(file_path), filename: filename)
    FileUtils.rm(file_path)
  end
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :user
  belongs_to :manual
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :manual

  validates :content, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :manuals
  has_many :procedures
  has_many :comments
  has_many :releases
  has_many :likes
  has_many :like_manuals, through: :likes, source: :manual
  has_many :reviews

  validates :nickname, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英数10文字以内で入力してください' },
                       length: { maximum: 10 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英字と半角数字の両方を含んでください' },
                       length: { minimum: 8 }, allow_nil: true

  def already_liked?(manual)
    likes.exists?(manual_id: manual.id)
  end

  def self.guest(guest_user)
    find_or_create_by!(email: "#{guest_user}@example.com") do |user|
      user.nickname = guest_user
      user.password = SecureRandom.hex(10)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :manual_find, only: [:create, :destroy]
  before_action :user_judge, only: [:create, :destroy]

  def create
    if !current_user.already_liked?(@manual)
      Like.create(like_params)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    if current_user.already_liked?(@manual)
      @like = Like.find_by(user_id: current_user.id, manual_id: params[:manual_id])
      @like.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def like_params
    params.permit.merge(user_id: current_user.id, manual_id: params[:manual_id])
  end

  def manual_find
    @manual = Manual.find(params[:manual_id])
  end

  def user_judge
    redirect_to root_path if current_user.id == @manual.user.id
  end
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :manual_find, only: [:show, :edit, :update, :destroy]
  before_action :user_judge, only: [:edit, :update, :destroy]
  before_action :show_user_judge, only: :show

  def index
    @releases = Release.includes(:user).order(created_at: 'DESC')
  end

  def new
    @manual = Manual.new
  end

  def create
    url = params[:manual][:image_url]
    converted_url = url.sub %r/data:((image|application)\/.{3,}),/, ''

    if url.blank? || url == converted_url
      @manual = Manual.new(manual_params)
    else
      @manual = Manual.new(manual_params_no_image)
      @manual.image_attach(converted_url)
    end

    if @manual.save
      @user = current_user
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @procedures = @manual.procedures.includes(:user)
    @comment = Comment.new
    @release = Release.new
    @review = Review.new
  end

  def edit
  end

  def update
    url = params[:manual][:image_url]
    converted_url = url.sub %r/data:((image|application)\/.{3,}),/, ''

    if url.blank? || url == converted_url
      move_page(manual_params)
    else
      move_page(manual_params_no_image)
      @manual.image_attach(converted_url)
    end
  end

  def destroy
    @manual.destroy
    @user = current_user
    redirect_to user_path(@user)
  end

  private

  def manual_params
    params.require(:manual).permit(:title, :category_id, :description, :image).merge(user_id: current_user.id)
  end

  def manual_params_no_image
    params.require(:manual).permit(:title, :category_id, :description).merge(user_id: current_user.id)
  end

  def manual_find
    @manual = Manual.find(params[:id])
  end

  def user_judge
    redirect_to root_path if current_user.id != @manual.user.id
  end

  def show_user_judge
    redirect_to root_path if @manual.release.blank? && (current_user.id != @manual.user.id)
  end

  def move_page(params_type)
    if @manual.update(params_type)
      redirect_to manual_path(@manual)
    else
      redirect_to edit_manual_path(@manual)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :user_find, only: :show
  before_action :user_judge, only: :show

  def show
  end

  private

  def user_find
    @user = User.find(params[:id])
  end

  def user_judge
    redirect_to root_path if current_user.id != @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManualApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_canvas.html.erb
<div>
  <canvas class="canvas" width="300px" height="300" id="crop-area"></canvas>
  <canvas class="canvas" width="300px" height="300" id="crop-canvas"></canvas>
  <ul class="crop-list">
    <li><a href="#" class="crop-size" data-size="75">0.25x</a></li>
    <li><a href="#" class="crop-size" data-size="150">0.5x</a></li>
    <li><a href="#" class="crop-size" data-size="225">0.75x</a></li>
    <li><a href="#" class="crop-size" data-size="300">1.0x</a></li>
  </ul>
</div>

<canvas class="canvas" width="500px" height="500px" id="canvas"></canvas>

<div class="image-contents">
  <span class="image-save" id="image-save">画像保存</span>
  <span id="saved-message">編集画像を保存しました</span>
  <ul class="paint-status">
    <li class="color">色：
      <a href="#" class="black" data-color="0, 0, 0, 1"></a>
      <a href="#" class="red" data-color="255, 0, 0, 1"></a>
      <a href="#" class="blue" data-color="0, 0, 255, 1"></a>
    </li>

    <li class="bold">太さ：
      <a href="#" class="small" data-bold="1">小</a>
      <a href="#" class="middle" data-bold="5">中</a>
      <a href="#" class="large" data-bold="10">大</a>
    </li>
  </ul>
</div>

app/views/shared/_comment.html.erb
<div class=<%= type %> style="" <%= type %>_id=<%= model.id %>>
  <div class="<%= type %>-header">
    <%= model.user.nickname %>
    <span class="<%= type %>-time"><%= l model.created_at %></span>
    <% if manual.user.id == current_user.id || model.user.id == current_user.id %>
      <%= link_to '削除', path, method: :delete, id: "#{type}-delete#{model.id}" %>
    <% else %>
      <%= link_to '削除', path, method: :delete, id: "#{type}-delete#{model.id}", style: "display: none;" %>
    <% end %>
  </div>
  <div class="<%= type %>-text"><%= model.content %></div>
</div>

app/views/shared/_comment_form.html.erb
<%= form_with model: model, url: path, id: "#{type}-form#{form_id}", local: true do |f| %>
  <div class="<%= type %>-form">
    <%= f.text_field :content, class: "#{type}-submit", id: "#{type}-text#{form_id}", placeholder: "  200文字以内" %>
    <%= f.submit '送信', class: "#{type}-submit-btn", manual_id: manual.id, procedure_id: form_id %>
  </div>
<% end %>

app/views/shared/_contents.html.erb
<div class="mypage-item">
  <div class="mypage-item-header">
    <%= link_to manual.title, manual_path(manual), class: "mypage-title" %>

    <%= render "shared/manual_action", manual: manual %>
  </div>

  <div class="mypage-image-content">
    <% if manual.image.attached? %>
      <%= link_to image_tag(manual.image.variant(resize: '250x250')), manual_path(manual) %>
    <% else %>
      <%= link_to image_tag("no_image.png", size: '250x240'), manual_path(manual) %>
    <% end %>
  </div>

  <div>【マニュアル説明】
    <% if user_signed_in? %>
      <% if current_user.id == manual.user.id %>
        <span>☆ <%= manual.likes.count %></span>
      <% elsif current_user.already_liked?(manual) %>
        <%= link_to '★', manual_like_path(manual, "#"), method: :delete %>
        <%= manual.like_users.count %>
      <% else %>
        <%= link_to '☆', manual_likes_path(manual), method: :post %>
        <%= manual.like_users.count %>
      <% end %>
    <% else %>
      <%= link_to '☆', manual_likes_path(manual), method: :post %>
      <%= manual.like_users.count %>
    <% end %>
  </div>
  <div class="mypage-description"><%= manual.description %></div>

  <div class="mypage-content-footer">
    <% if user_signed_in? && manual.user.id == current_user.id %>
      <div class="mypage-manual-user">投稿者：あなたの投稿です</div>
    <% else %>
      <div class="mypage-manual-user">投稿者：<%= manual.user.nickname %></div>
    <% end %>
    <div class="mypage-category">#<%= manual.category.name %></div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div style="color: red;">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="new-manual-name">【<%= title_name %>】
  <span class="need-icon">必須</span>
</div>
<%= f.text_field :title, placeholder: "  #{title_count}文字以内", autofocus: true, class: "form-manual-name" %>

<% if !request.path.include?('procedures') %>
  <div class="new-manual-category">【カテゴリー】
    <span class="need-icon">必須</span>
  </div>
  <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "form-manual-category"}) %>
<% end %>

<div class="new-manual-image">【画像】</div>
<div class="new-image-text">クリックして画像を選択してください</div>
<%= f.file_field :image, class: "form-manual-image", id: "file-field" %>
<%= f.hidden_field :image_url, value: "", id: "image-form" %>

<%= render "shared/canvas" %>

<div class="new-manual-description">【<%= description_name %>】</div>
<%= f.text_area :description, placeholder: "  #{description_count}文字以内", class: "form-manual-description" %>

<div>
  <%= f.submit submit_text, class: "new-submit-btn" %>
</div>

app/views/shared/_header.html.erb
<header class="header-content">
  <div>
    <%= link_to 'マニュアル作成アプリ', root_path, class: "header-title" %>
  </div>

  <div class="user-content">
    <%# Show below in the case of log out %>
    <% if !user_signed_in? %>
      <div class="user-list">
        <%= link_to 'ログイン', new_user_session_path, class: "user-item" %>
        <%= link_to '新規登録', new_user_registration_path, class: "user-item" %>
      </div>

    <%# Show below int the case of log in %>
    <% else %>
      <div class="user-list">
        <span class="user-item">▲<%= current_user.nickname %>
          <ul>
            <li><%= link_to '編集', edit_user_registration_path, class: "user-edit" %></li>
            <li><%= link_to 'お気に入り', user_likes_path(current_user), class: "user-likes" %></li>
            <li><%= link_to 'マイページ', user_path(current_user), class: "user-mypage" %></li>
          </ul>
        </span>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "user-item" %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_image_content.html.erb
<% if model.image.attached? %>
  <%= image_tag(model.image.variant(resize: '300x300')) %>
<% else %>
  <%= image_tag("no_image.png", size: '300x280') %>
<% end %>

app/views/shared/_manual_action.html.erb
<% if user_signed_in? && manual.user.id == current_user.id %>
  <div class="show-release">
    <% if manual.release.blank? %>
      <%= link_to '一般公開する', manual_releases_path(manual), method: :post, class: "release-btn", data: {confirm: "一般公開すると全ユーザーから情報が閲覧可能になります。\n本当によろしいですか？"} %>
    <% else %>
      <%= link_to '非公開にする', manual_release_path(manual, manual.release.id), method: :delete, class: "release-btn" %>
    <% end %>
  </div>
  <ul class="procedure-top-right">
    <li><%= link_to '編集', edit_manual_path(manual) %></li>
    <li><%= link_to '削除', manual_path(manual), method: :delete, data: {confirm: "本当に削除しますか？"} %></li>
  </ul>
<% end %>