config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "manuals#index"
  resources :manuals, except: :index do
    resources :procedures, except: [:index, :show] do
      resources :comments, only: [:create, :destroy]
    end
    resources :releases, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resources :likes, only: :index
  end
end

app/models/manual.rb
class Manual < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :release, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :reviews, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :title, length: { maximum: 20 }
    validates :category_id, numericality: { other_than: 0, message: 'を選択してください' }
  end
  validates :description, length: { maximum: 160 }

  def image_attach(converted_url)
    decoded_url = Base64.decode64(converted_url)
    filename = Time.zone.now.to_s + '.png'

    if Rails.env == 'development'
      # Local environment
      file_path = "#{Rails.root}/tmp/images/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    elsif Rails.env == 'production'
      # Production environment
      file_path = "/tmp/#{filename}"
      image_attach_process(decoded_url, filename, file_path)
    end
  end

  def image_attach_process(decoded_url, filename, file_path)
    File.open(file_path, 'wb') do |f|
      f.write(decoded_url)
    end
    image.attach(io: File.open(file_path), filename: filename)
    FileUtils.rm(file_path)
  end
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :manual_find, only: [:show, :edit, :update, :destroy]
  before_action :user_judge, only: [:edit, :update, :destroy]
  before_action :show_user_judge, only: :show

  def index
    @releases = Release.includes(:user).order(created_at: 'DESC')
  end

  def new
    @manual = Manual.new
  end

  def create
    url = params[:manual][:image_url]
    converted_url = url.sub %r/data:((image|application)\/.{3,}),/, ''

    if url.blank? || url == converted_url
      @manual = Manual.new(manual_params)
    else
      @manual = Manual.new(manual_params_no_image)
      @manual.image_attach(converted_url)
    end

    if @manual.save
      @user = current_user
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @procedures = @manual.procedures.includes(:user)
    @comment = Comment.new
    @release = Release.new
    @review = Review.new
  end

  def edit
  end

  def update
    url = params[:manual][:image_url]
    converted_url = url.sub %r/data:((image|application)\/.{3,}),/, ''

    if url.blank? || url == converted_url
      move_page(manual_params)
    else
      move_page(manual_params_no_image)
      @manual.image_attach(converted_url)
    end
  end

  def destroy
    @manual.destroy
    @user = current_user
    redirect_to user_path(@user)
  end

  private

  def manual_params
    params.require(:manual).permit(:title, :category_id, :description, :image).merge(user_id: current_user.id)
  end

  def manual_params_no_image
    params.require(:manual).permit(:title, :category_id, :description).merge(user_id: current_user.id)
  end

  def manual_find
    @manual = Manual.find(params[:id])
  end

  def user_judge
    redirect_to root_path if current_user.id != @manual.user.id
  end

  def show_user_judge
    redirect_to root_path if @manual.release.blank? && (current_user.id != @manual.user.id)
  end

  def move_page(params_type)
    if @manual.update(params_type)
      redirect_to manual_path(@manual)
    else
      redirect_to edit_manual_path(@manual)
    end
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/manuals/edit.html.erb
<%= render "shared/header" %>

<%= link_to 'マニュアル詳細画面に戻る', manual_path(@manual), class: "edit-to-new" %>
<div class="new-page-title"> 編集したいマニュアルの情報を入力</div>

<div class="form-manual-contents">
  <%= form_with model: @manual, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%= render 'shared/form', {f: f, title_name: 'マニュアル名', title_count: '20', description_name: 'マニュアル説明', description_count: '160', submit_text: '編集完了'} %>
  <% end %>
</div>

app/views/manuals/index.html.erb
<%= render "shared/header" %>

<div class="main-content">
  <%= link_to new_manual_path, class: "manual-create" do %>
    <div class="main-item">
      マニュアル<br>新規作成
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to user_path(current_user), class: "mypage" do %>
      <div class="main-item">
        マイページ<br>マニュアル一覧
      </div>
    <% end %>
  <% end %>
</div>

<div class="mypage-contents">
  <% @releases.each do |release| %>
    <%= render partial: "shared/contents", locals: {manual: release.manual} %>
  <% end %>
</div>

app/views/manuals/new.html.erb
<%= render "shared/header" %>

<div class="new-page-title">作成するマニュアルの情報を入力</div>

<div class="form-manual-contents">
  <%= form_with model: @manual, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%= render 'shared/form', {f: f, title_name: 'マニュアル名', title_count: '20', description_name: 'マニュアル説明', description_count: '160', submit_text: '作成完了'} %>
  <% end %>
</div>

app/views/manuals/show.html.erb
<%= render "shared/header" %>

<div class="procedure-top">
  <div class="procedure-top-title"><%= @manual.title %></div>
  <ul class="procedure-top-middle">
    <li class="procedure-top-category">#<%= @manual.category.name %></li>
    <% if @manual.user.id == current_user.id %>
      <li><%= link_to '手順を追加', new_manual_procedure_path(@manual), class: "procedure-create" %></li>
    <% end %>
  </ul>

  <%= render "shared/manual_action", manual: @manual %>
</div>

<div class="procedure-top-contents">
  <div class="procedure-top-image">
    <%= render "shared/image_content", model: @manual %>
  </div>

  <div class="procedure-top-item">
    <p>【マニュアル説明】</p>
    <div class="procedure-top-description"><%= @manual.description %></div>
  </div>

  <div class="review-contents">
    <div class="review-index">
      <% @manual.reviews.each do |review| %>
        <%= render "shared/comment", {manual: @manual, model: review, type: 'review', path: manual_review_path(@manual, review)} %>
      <% end %>
      <div id="review-list"></div>
    </div>
    <%= render "shared/comment_form", {manual: @manual, model: @review, type: 'review', path: manual_reviews_path(@manual), form_id: ''} %>
  </div>
</div>

<% @procedures.each_with_index do |procedure, index| %>
  <div class="procedure-contents">
    <div class="procedure-item">
      <div class="procedure-item-header">
        <div class="procedure-number"><%= index+1 %>．</div>
        <div class="procedure-title"><%= procedure.title %></div>
        <% if @manual.user.id == current_user.id %>
          <ul>
            <li><%= link_to '編集', edit_manual_procedure_path(@manual, procedure) %></li>
            <li><%= link_to '削除', manual_procedure_path(@manual, procedure), method: :delete, data: {confirm: "本当に削除しますか？"} %></li>
          </ul>
        <% end %>
      </div>

      <div class="procedure-description"><%= procedure.description %></div>
    </div>

    <div class="procedure-top-image">
      <%= render "shared/image_content", model: procedure %>
    </div>

    <div class="comment-contents">
      <div class="comment-index">
        <% procedure.comments.each do |comment| %>
          <%= render "shared/comment", {manual: @manual, procedure: procedure, model: comment, type: 'comment', path: manual_procedure_comment_path(@manual, procedure, comment)} %>
        <% end %>
        <div id="comment-list<%= procedure.id %>"></div>
      </div>
      <%= render "shared/comment_form", {manual: @manual, procedure: procedure, model: @comment, type: 'comment', path: manual_procedure_comments_path(@manual, procedure), form_id: procedure.id} %>
    </div>
  </div>
<% end %>

<% if @manual.user.id == current_user.id %>
  <%= link_to '手順を追加', new_manual_procedure_path(@manual), class: "procedure-create" %>
<% end %>